spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://localhost:3307/manage_homestay?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    hikari: # Connection poll
      max-lifetime: 300000      # 5 phút
      idle-timeout: 60000       # 1 phút
      validation-timeout: 5000  # 5 giây
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:8080
    title: Backend service
    version: 1.0.0

# Generate HMAC Authentication Code: https://www.devglan.com/online-tools/hmac-sha256-online
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: Y0bUnOe4b6zjB8x3YytJm1lqjzPqZxPjQWCUhNQ9UjA=
  refreshKey: X4Q9xAqN1J8kN7+qv93y7Jt3RHfF0a8w2uKgp1qY8mY=